### ISSUE TITLE
question on steps ( /step-count/summary endpoint)

### ISSUE THREAD

**Issue by lila** [vishnuravi/fitbit-to-openmhealth#15]
When i get my steps from fitbit using the timeseries intraday api:

```
steps = fitbit.time_series(
            "activities/steps", base_date=today, period=arguments["--range"]
        )
```

that looks something like this:

```
{
    "activities-steps": [
        {
            "dateTime": "2021-08-23",
            "value": "4511"
        }
    ],
    "activities-steps-intraday": {
        "dataset": [
            {
                "time": "00:00:00",
                "value": 0
            },
...
```
this is basicaly giving me a minute by minute step count.

When i convert that using the /step-count/intraday, i got a lot of records.  it does look like you are filtering out the zero step count minutes.  but min-by-min is probably not that useful.  but switching to /step-count/summary, this generates an "internal server error".

```
$ curl -X POST -H "Content-Type: application/json" -d @./mysteps.json https://fitbit2openmhealth-4srwo7mzta-uc.a.run.app/step-count/summary
{"timestamp":"2021-08-23T15:00:06.935+00:00","status":500,"error":"Internal Server Error","path":"/step-count/summary"}
```

According to the readme, it says that the input to the /step-count/intraday and /step-count/summary are the same.  is that correct?

**Comment by vishnuravi** [comment]
Yes, the input is the same. The `/step-count/summary` endpoint uses the daily sum which is in the "activities-steps" property in the sample data you have. 

I think the issue you are running into is that the "value" property contains the step count value as a string, but the mapper is expecting it as an integer. If you remove the quotes there, it may solve the issue. I am not sure why the Fitbit Web API gave it to you as a string since the [examples](https://dev.fitbit.com/build/reference/web-api/activity/#activity-time-series) provide the values as integers. This is an easy fix I can take care of in the mapper. 

I also apologize for the quality of the error message. It should have been more descriptive and I'll address that.

**Comment by lila** [comment]
yes, that works!  thank you!

**Comment by lila** [comment]
for the record, your error message was:

```
org.openmhealth.mapper.common.IncompatibleJsonNodeMappingException: The field 'value' with value '4511' doesn't have expected type 'class java.lang.Integer' in node '{"dateTime":"2021-08-23","value":"4511"}'.
```

cloudrun does highlight the error logs. i just hadn't looked yet... cheers,

- karan
